<?php

declare(strict_types=1);

namespace App\Services\Ai;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Throwable;

class VideoGenerator
{
    private string $provider;

    private string $model;

    private string $apiKey;

    private ?string $baseUrl;

    public function __construct()
    {
        $this->provider = (string) config('ai.video.provider', 'gemini');
        $this->model = (string) config('ai.video.model', 'veo-3.0-generate-preview');
        $this->apiKey = (string) config('ai.video.api_key', '');
        $this->baseUrl = config('ai.video.base_url');
    }

    /**
     * Generate a short video using the configured provider.
     *
     * @return array{video_path: string|null, error: string|null}
     */
    public function generate(string $prompt, string $size = '9:16', string $quality = '720p'): array
    {
        if ($this->apiKey === '') {
            return ['video_path' => null, 'error' => 'Video generator API key is not configured.'];
        }

        try {
            return match ($this->provider) {
                'gemini' => $this->generateGemini($prompt, $size, $quality),
                'openai' => $this->generateOpenAI($prompt, $size, $quality),
                default => ['video_path' => null, 'error' => "Unsupported video provider: {$this->provider}"],
            };
        } catch (Throwable $e) {
            Log::error('VideoGenerator: generation failed', [
                'provider' => $this->provider,
                'model' => $this->model,
                'error' => $e->getMessage(),
            ]);

            return ['video_path' => null, 'error' => $e->getMessage()];
        }
    }

    /**
     * @return array{video_path: string|null, error: string|null}
     */
    private function generateGemini(string $prompt, string $size, string $quality): array
    {
        $baseUrl = $this->baseUrl ?: 'https://generativelanguage.googleapis.com/v1beta';
        $url = "{$baseUrl}/models/{$this->model}:generateContent?key={$this->apiKey}";

        $aspectRatio = match ($size) {
            '1:1' => '1:1',
            '9:16' => '9:16',
            '16:9' => '16:9',
            default => '9:16',
        };

        $response = Http::timeout(300)
            ->post($url, [
                'contents' => [
                    [
                        'parts' => [
                            ['text' => $prompt],
                        ],
                    ],
                ],
                'generationConfig' => [
                    'responseModalities' => ['TEXT', 'VIDEO'],
                    'videoConfig' => [
                        'aspectRatio' => $aspectRatio,
                        'personGeneration' => 'allow_all',
                    ],
                ],
            ]);

        if ($response->failed()) {
            $error = $response->json('error.message') ?? "HTTP {$response->status()}";

            return ['video_path' => null, 'error' => "Gemini API error: {$error}"];
        }

        $candidates = $response->json('candidates', []);

        if (empty($candidates)) {
            return ['video_path' => null, 'error' => 'No video generated by Gemini.'];
        }

        $parts = $candidates[0]['content']['parts'] ?? [];

        foreach ($parts as $part) {
            if (isset($part['inlineData']['data']) && isset($part['inlineData']['mimeType'])) {
                $mimeType = $part['inlineData']['mimeType'];
                $extension = str_contains($mimeType, 'webm') ? 'webm' : 'mp4';
                $filename = 'videos/'.Str::uuid().".{$extension}";
                $bytes = base64_decode($part['inlineData']['data'], true);

                if ($bytes !== false && $bytes !== '') {
                    Storage::disk('public')->put($filename, $bytes);

                    return ['video_path' => $filename, 'error' => null];
                }
            }
        }

        return ['video_path' => null, 'error' => 'No video data found in Gemini response.'];
    }

    /**
     * @return array{video_path: string|null, error: string|null}
     */
    private function generateOpenAI(string $prompt, string $size, string $quality): array
    {
        $baseUrl = $this->baseUrl ?: 'https://api.openai.com/v1';
        $url = "{$baseUrl}/video/generations";

        $resolution = match ($quality) {
            '1080p' => '1080p',
            default => '720p',
        };

        $response = Http::withHeaders([
            'Authorization' => "Bearer {$this->apiKey}",
            'Content-Type' => 'application/json',
        ])->timeout(300)->post($url, [
            'model' => $this->model,
            'prompt' => $prompt,
            'size' => $size === '9:16' ? '768x1344' : ($size === '1:1' ? '1024x1024' : '1344x768'),
            'quality' => $resolution,
        ]);

        if ($response->failed()) {
            $error = $response->json('error.message') ?? "HTTP {$response->status()}";

            return ['video_path' => null, 'error' => "OpenAI API error: {$error}"];
        }

        $videoUrl = $response->json('data.0.url');

        if (! $videoUrl) {
            return ['video_path' => null, 'error' => 'No video URL in OpenAI response.'];
        }

        $videoResponse = Http::timeout(120)->get($videoUrl);

        if ($videoResponse->failed()) {
            return ['video_path' => null, 'error' => 'Failed to download generated video.'];
        }

        $filename = 'videos/'.Str::uuid().'.mp4';
        Storage::disk('public')->put($filename, $videoResponse->body());

        return ['video_path' => $filename, 'error' => null];
    }
}
